# -*- coding: utf-8 -*-
"""CPL7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pNzH_4YM6CN5AKtlvl16fk-XpNU4Doz
"""

# CELL 1
!nvidia-smi

# CELL 2
import numpy as np
from numba import cuda, float32
import math

# Define block size as a constant.
# CUDA shared memory allocation in Numba requires the size to be known at compile time.
THREADS_PER_BLOCK = 256

# CELL 3
@cuda.jit
def reduce_mult_kernel(d_input, d_output):
    # Allocate shared memory for the block.
    # Size must match THREADS_PER_BLOCK.
    sdata = cuda.shared.array(THREADS_PER_BLOCK, dtype=float32)

    # Get thread and block indices
    tid = cuda.threadIdx.x
    global_idx = cuda.grid(1)

    # 1. Load data into shared memory
    # If the global index is within the array bounds, load the value.
    # Otherwise, load 1.0 (the identity element for multiplication).
    if global_idx < d_input.size:
        sdata[tid] = d_input[global_idx]
    else:
        sdata[tid] = 1.0

    # Synchronize to ensure all threads have finished writing to shared memory
    cuda.syncthreads()

    # 2. Perform tree-based reduction in shared memory
    stride = cuda.blockDim.x // 2
    while stride > 0:
        if tid < stride:
            sdata[tid] *= sdata[tid + stride]

        # Synchronize at each level of the tree
        cuda.syncthreads()

        # Halve the stride for the next iteration
        stride //= 2

    # 3. Write the block's reduced result back to global memory
    if tid == 0:
        d_output[cuda.blockIdx.x] = sdata[0]

# CELL 4
# 1. Generate Input Data
# We use an array size that is not perfectly divisible by our block size to test our bounds checking.
N = 10000
# Creating an array of 1.0001 so the final product is roughly 2.71 (close to e)
h_input = np.full(N, 1.0001, dtype=np.float32)

# 2. Calculate Grid Dimensions
blocks_per_grid = math.ceil(N / THREADS_PER_BLOCK)

# 3. Allocate Output Array (One result per block)
h_output = np.zeros(blocks_per_grid, dtype=np.float32)

# 4. Transfer data to Device (GPU)
d_input = cuda.to_device(h_input)
d_output = cuda.device_array_like(h_output)

# 5. Launch the Kernel
reduce_mult_kernel[blocks_per_grid, THREADS_PER_BLOCK](d_input, d_output)

# 6. Copy partial results back to Host (CPU)
d_output.copy_to_host(h_output)

# 7. Final Reduction on CPU
# The GPU has reduced the array from size N to size `blocks_per_grid`.
# We finish the final few multiplications on the CPU (standard practice for small arrays).
final_gpu_result = np.prod(h_output)

print(f"Original Array Size: {N}")
print(f"Blocks Launched (Partial Results): {blocks_per_grid}")
print(f"Final GPU Reduction Result: {final_gpu_result}")

# CELL 5
# Calculate the expected result using CPU NumPy
expected_result = np.prod(h_input)

print(f"GPU Result:      {final_gpu_result:.6f}")
print(f"Expected Result: {expected_result:.6f}")

# Check if they are close (accounting for floating point inaccuracies)
if np.isclose(final_gpu_result, expected_result, rtol=1e-5):
    print("\nSUCCESS: GPU and CPU results match!")
else:
    print("\nERROR: Results do not match.")