# -*- coding: utf-8 -*-
"""Upper Triangular Matrix End Sem Practical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehTnS9ET3AUiSs76QtmHewEtMsxt7atV
"""

# Cell 1: Verify GPU runtime
# Runtime → Change runtime type → T4 GPU

import subprocess
result = subprocess.run(['nvidia-smi'], capture_output=True, text=True)
print(result.stdout)

# Also check CUDA version
import torch
print(f"CUDA Available: {torch.cuda.is_available()}")
print(f"GPU: {torch.cuda.get_device_name(0)}")

# Cell 2: Install CuPy (pre-built for CUDA 12.x on Colab T4)
!pip install cupy-cuda12x -q

# Verify installation
import cupy as cp
print(f"CuPy version : {cp.__version__}")
print(f"CUDA version : {cp.cuda.runtime.runtimeGetVersion()}")
print(f"GPU Device   : {cp.cuda.Device(0).attributes}")

# Cell 3: Create the input matrix on GPU directly
import cupy as cp
import numpy as np

N = 1024  # Matrix dimension

# Generate random float32 matrix directly on GPU (faster than CPU→GPU transfer)
cp.random.seed(42)
A_gpu = cp.random.randint(1, 100, size=(N, N), dtype=cp.int32)

print(f"Matrix shape : {A_gpu.shape}")
print(f"Matrix dtype : {A_gpu.dtype}")
print(f"Memory used  : {A_gpu.nbytes / (1024**2):.2f} MB")

# Preview top-left 6×6 corner on CPU
print("\nOriginal Matrix (top-left 6×6):")
print(cp.asnumpy(A_gpu[:6, :6]))

# Cell 4: Write the CUDA kernel using Numba
# Each thread handles ONE cell → checks if col >= row

from numba import cuda
import numpy as np
import math

@cuda.jit
def upper_triangular_kernel(A, result, n):
    """
    CUDA kernel: each thread processes ONE cell (row, col).

    Thread mapping:
      - blockIdx.x  → which block along X (column direction)
      - blockIdx.y  → which block along Y (row direction)
      - threadIdx.x → thread column within block
      - threadIdx.y → thread row within block
    """
    # Compute global row and column index for THIS thread
    row = cuda.blockIdx.y * cuda.blockDim.y + cuda.threadIdx.y
    col = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.x

    # Boundary check: ensure thread maps to a valid cell
    if row < n and col < n:
        if col >= row:
            # Upper triangle (including diagonal): keep original value
            result[row, col] = A[row, col]
        else:
            # Lower triangle: set to zero
            result[row, col] = 0

print("✅ Numba CUDA kernel compiled successfully.")
print("\nKernel logic:")
print("  Thread (row, col) → result[row,col] = A[row,col] if col >= row else 0")

# Cell 5: Configure CUDA thread blocks and grid dimensions

N = 1024

# Block size: 32×32 = 1024 threads per block (hardware maximum)
BLOCK_DIM_X = 32
BLOCK_DIM_Y = 32
threads_per_block = (BLOCK_DIM_X, BLOCK_DIM_Y)

# Grid size: ceil(N / BLOCK_DIM) blocks in each dimension
GRID_DIM_X = math.ceil(N / BLOCK_DIM_X)   # = 32
GRID_DIM_Y = math.ceil(N / BLOCK_DIM_Y)   # = 32
blocks_per_grid = (GRID_DIM_X, GRID_DIM_Y)

total_threads = (GRID_DIM_X * BLOCK_DIM_X) * (GRID_DIM_Y * BLOCK_DIM_Y)

print("=" * 45)
print("  CUDA Launch Configuration")
print("=" * 45)
print(f"  Matrix size        : {N} × {N} = {N*N:,} cells")
print(f"  Threads per block  : {BLOCK_DIM_X} × {BLOCK_DIM_Y} = {BLOCK_DIM_X*BLOCK_DIM_Y}")
print(f"  Blocks in grid     : {GRID_DIM_X} × {GRID_DIM_Y} = {GRID_DIM_X*GRID_DIM_Y}")
print(f"  Total threads      : {total_threads:,}")
print(f"  Cells per thread   : 1 (one-to-one mapping)")
print("=" * 45)

# Cell 6: Allocate memory and run the kernel

# Transfer input from CuPy to NumPy for Numba
A_cpu = cp.asnumpy(A_gpu)

# Allocate pinned device arrays for Numba
A_device      = cuda.to_device(A_cpu)
result_device = cuda.device_array((N, N), dtype=np.int32)

# ─── LAUNCH KERNEL ───────────────────────────────────────────
upper_triangular_kernel[blocks_per_grid, threads_per_block](
    A_device, result_device, N
)

# Synchronize GPU before reading results
cuda.synchronize()

# Copy result back to CPU
result_cpu = result_device.copy_to_host()

print("✅ Kernel executed successfully!")
print(f"\nResult shape : {result_cpu.shape}")
print(f"Result dtype : {result_cpu.dtype}")

# Cell 7: Verify output against NumPy's triu (ground truth)

expected = np.triu(A_cpu)   # NumPy reference implementation

if np.array_equal(result_cpu, expected):
    print("✅ VERIFICATION PASSED — CUDA result matches NumPy triu() exactly!")
else:
    diff = np.sum(result_cpu != expected)
    print(f"❌ MISMATCH — {diff} cells differ out of {N*N}")

# Show first 6×6 corner comparison
print("\n--- Original Matrix (top-left 6×6) ---")
print(A_cpu[:6, :6])

print("\n--- CUDA Upper Triangular (top-left 6×6) ---")
print(result_cpu[:6, :6])

print("\n--- NumPy triu Reference (top-left 6×6) ---")
print(expected[:6, :6])

# Cell 8: Benchmark CUDA vs NumPy vs CuPy

import time

WARMUP = 5
RUNS   = 50

# ── Warmup ──────────────────────────────────────────
for _ in range(WARMUP):
    upper_triangular_kernel[blocks_per_grid, threads_per_block](
        A_device, result_device, N
    )
    cuda.synchronize()

# ── CUDA (Numba kernel) ──────────────────────────────
t0 = time.perf_counter()
for _ in range(RUNS):
    upper_triangular_kernel[blocks_per_grid, threads_per_block](
        A_device, result_device, N
    )
    cuda.synchronize()
cuda_time = (time.perf_counter() - t0) / RUNS * 1000

# ── CuPy triu (GPU, optimized library) ──────────────
cp.cuda.Stream.null.synchronize()
t0 = time.perf_counter()
for _ in range(RUNS):
    R = cp.triu(A_gpu)
    cp.cuda.Stream.null.synchronize()
cupy_time = (time.perf_counter() - t0) / RUNS * 1000

# ── NumPy triu (CPU) ─────────────────────────────────
t0 = time.perf_counter()
for _ in range(RUNS):
    _ = np.triu(A_cpu)
numpy_time = (time.perf_counter() - t0) / RUNS * 1000

print("=" * 48)
print("  Performance Benchmark (1024×1024 int32)")
print("=" * 48)
print(f"  CUDA Numba kernel  : {cuda_time:.4f} ms")
print(f"  CuPy triu (GPU)    : {cupy_time:.4f} ms")
print(f"  NumPy triu (CPU)   : {numpy_time:.4f} ms")
print(f"\n  Speedup vs NumPy   : {numpy_time/cuda_time:.1f}×")
print("=" * 48)

# Cell 9: Visualize original vs upper triangular

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.patch.set_facecolor('#0d1117')

titles  = ["Original Matrix", "CUDA Upper Triangular", "Difference (should be zero)"]
data    = [A_cpu, result_cpu, A_cpu - result_cpu]
cmaps   = ['viridis', 'plasma', 'RdBu']

for ax, title, d, cmap in zip(axes, titles, data, cmaps):
    ax.set_facecolor('#0d1117')
    im = ax.imshow(d, cmap=cmap, interpolation='nearest', aspect='auto')
    ax.set_title(title, color='white', fontsize=13, pad=10)
    ax.set_xlabel("Column", color='#aaaaaa')
    ax.set_ylabel("Row", color='#aaaaaa')
    ax.tick_params(colors='#aaaaaa')
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    for spine in ax.spines.values():
        spine.set_edgecolor('#333')

plt.suptitle("CUDA Upper Triangular Matrix Extraction  |  1024×1024",
             color='white', fontsize=15, y=1.02)
plt.tight_layout()
plt.savefig("upper_triangular_result.png", dpi=150,
            bbox_inches='tight', facecolor='#0d1117')
plt.show()
print("✅ Visualization saved.")

# Cell 10: Pure CuPy version (no kernel writing needed)
# Uses cuBLAS/cuSPARSE under the hood

import cupy as cp

A_gpu = cp.random.randint(1, 100, size=(1024, 1024), dtype=cp.int32)

# Method 1: cp.triu  (fastest)
upper_cupy = cp.triu(A_gpu)

# Method 2: Using a mask (educational)
rows = cp.arange(1024)[:, None]   # shape (1024, 1)
cols = cp.arange(1024)[None, :]   # shape (1, 1024)
mask = cols >= rows               # broadcast → shape (1024, 1024) bool
upper_masked = A_gpu * mask

# Verify both methods match
assert cp.array_equal(upper_cupy, upper_masked), "Mismatch!"
print("✅ Both CuPy methods produce identical results.")
print(f"\nupper_cupy shape : {upper_cupy.shape}")
print(f"Non-zero elements: {int(cp.count_nonzero(upper_cupy)):,}")
print(f"Expected (N*(N+1)/2): {1024*1025//2:,}")